### ISSUE TITLE
RTNETLINK answers: Operation not permitted

### ISSUE THREAD

**Issue by rass92** [vcgomes/iproute2#1]
Hi Mr Vinicius,

I am trying to use tc taprio by running the following command

```
tc qdisc replace dev enp3s0f1 parent root handle 100 taprio num_tc 2 map 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 queues 1@0 1@1 base-time 1554445635681310809 sched-entry S 01 1000000 sched-entry S 02 1000000 clockid CLOCK_REALTIME
```
but I am having the following error

```
RTNETLINK answers: Operation not permitted
```

I am using Ubuntu 20.04, wth the kernel 5.10.14-rt27.

Here I have the flag config_net_sch_taprio=y activate

and as another way I use the kernel 5.8.0-43-generic
and incorporte the module sch_taprio.ko with the command

```
sudo modprobe sch_taprio
sudo insmod /lib/modules/5.8.0-43-generic/kernel/net/sched/sch_taprio.ko
```

and still got the same error

I have tried to use other configuration with taprio but still got the same issue

Can you help to see what I am doing wrong here?

**Comment by vcgomes** [comment]
To replace the qdisc you need the CAP_NET_ADMIN capability, so the first thing that comes to mind is that adding `sudo` to the command should work. Can you try that and see if it works?

**Comment by rass92** [comment]
Hi Mr Vinicius,

I try to use sudo and I got the following error

```
RTNETLINK answers: Operation not supported
```

I try in both the 5.10.14-rt27 with the config_net_sch_taprio=y flag activate

and in the 5.8.0-43-generic where I incorporate the module sch_taprio.ko

In both I got the same error

**Comment by vcgomes** [comment]
One thing that could be is that the NIC you are using doesn't support multiple queues. Can you check the output of `sudo ethtool -l enp3s0f1`? taprio requires a NIC with multiple queues, for the case of your example configuration, it would need a NIC with at least 2 queues.

**Comment by rass92** [comment]
Hi Vinicius

Yes I think that is the problem
the output of the command is
```
Channel parameters for enp3s0f1:
Cannot get device channel parameters
: Operation not supported
```
I have a question, the command with `ethtool` is the same as when I run the following command?
```
$ ls /sys/class/net/enp3s0f1/queues/
```
that gives the output
```
rx-0  tx-0
```
meaning that is just one tx queue and one rx queue?

Thank you

**Comment by vcgomes** [comment]
If the NIC doesn't support the "get channels" operation and `$ ls /sys/class/net/enp3s0f1/queues/` gives you that output, then, it indeed has only one queue.

The way taprio works it needs a bit of help from the hardware, with multiple queues, it can separate traffic from separate traffic classes into separate queues, and only allow dequeuing packets from a subset of those queues during an interval.

**Comment by rass92** [comment]
Thank you very much Mr Vinicius for the answer, we can close this issue
